### ISSUE TITLE
Melhorias no Dockerfile

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [FGA-GCES/guardioes-api#2]
A versão atual do Dockerfile gera uma imagem muito grande (1.25gb+) com diversas dependências desnecessárias.
![image](https://user-images.githubusercontent.com/37124267/94855773-64f41f00-0405-11eb-93ae-bd04e45f177c.png)

Pontos de melhoria:
- Utilizar uma imagem Ruby baseada em Alpine Linux. Alpine possui menos dependências instaladas, consequentemente uma surface área menor para ser atacada e potencialmente deploys mais rápidos, dependendo da configuração de cache.
- Utilizar Dockerfile com multiplos stages. Algumas libs(por exemplo nokogiri) necessitam de certas dependências pesadas para serem instaladas, entretanto, após a fase de build, tais dependências são desnecessárias. Utilizando um Dockerfile com múltiplios stages é possível realizar a instalação dessas libs, sem que as dependências desnecessárias cheguem na imagem final.
- Adicionar .dockerignore.
- Remover passos extra desnecessários, por exemplo: 
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
Poderiam ser simplificados para uma única linha, evitando gerar camadas desnecessárias.
- O script entrypoint.sh pode ser desnecessário, considerando que o docker-compose executa o mesmo script no command.

**Comment by jlucassr** [comment]
Como a melhoria foi implementada, issue feita.
