### ISSUE TITLE
Estudar viabilidade da utilização do Kibana

### ISSUE THREAD

**Issue by icarooliv** [FGA-GCES/guardioes-api#4]
Atualmente, os gestores precisam visualizar ou filtrar manualmente os dados específicos para a entidade que representam. 

Seria uma boa contribuição verificar como criar dashboard de forma escalável para que cada gestor veja apenas os dados que sejam de seu interesse.

Também, ao criar uma visualização de dados nova no Kibana, essa visualização deve estar disponível para todos os gestores já com os dados filtrados.

- [x] Verificar criação de dashboars específicos para cada entidade 
- [x] Verificar versionamento dos gráficos no Kibana
- [x] Verificar criação de roles no Kibana
- [x] Verificar integração do kibana com o guardiões web

**Comment by icarooliv** [comment]
Pontos de melhoria:

* Durante a execução dos ambientes, percebemos que os docker-compose do web e da api não estavam conectados por uma network. Então os containers de cada aplicação não estavam conseguindo se conectar. Seria uma boa contribuição configurar esse ambiente de forma que os serviços consigam se comunicar entre si.

* Ao verificar a  arquitetura do frontend web, percebemos que estava sendo utilizado um iframe para exbir os gráficos do Kibana. Precisamos investigar com a equipe se essa abordagem pode escalar e também se pode resultar em alguma vulnerabilidade (um usuário poder visualizar dados de outra entidade, por exemplo).
    - Caso essa solução não seja escalável, temos a opção de investigar novas abordagens como por exemplo o projeto Chaos/GrimoireLab.
* O repositório web apresentava alguns problemas de módulos não utilizados e arquivos antigos que já foram substituidos por novas implementações além de alguns bugs nos do formulário de cadastro.

**Comment by icarooliv** [comment]
Referências/Links Uteis

- https://chaoss.github.io/grimoirelab/
- https://stackoverflow.com/questions/51876291/version-control-kibana-saved-objects
- https://www.elastic.co/pt/blog/elasticsearch-versioning-support
- https://discuss.elastic.co/t/version-control-and-backup-of-dashboard-visualization-query-object/229148 
- https://www.elastic.co/guide/en/kibana/current/space-rbac-tutorial.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/built-in-roles.html
- https://www.elastic.co/guide/en/kibana/current/kibana-role-management.html

**Comment by GabrielOak** [comment]
Na conversa com o João Gabriel, foi apresentado o Metabase como uma alternativa ao Kibana. Pela conversa inicial, o Metabase
consegue suprir as necessidades do time de desenvolvimento e com isso, foi sugerido subir uma versão de teste do Metabase.

Pontos positivos do Metabase em relação o Kibana:
 - No Metabase o administrador consegue privar os dados do usuário
 - É possível criar gráficos através de uma consulta SQL
 - No Metabase pode ser feita conexão direta com o banco de dados, não necessitando manter 2 bancos de dados (ElasticSearch)

Pontos de atenção:  
 - Se o Metabase vai ter os mapas necessários
 - Se o Metabase consegue suprir com os gráficos necessários 
 - Se o Metabase vai consumir muito de servidor
 - Se o Metabase vai conseguir ser tão rápido como o ElasticSearch

**Comment by icarooliv** [comment]
Issue transferida para o fork do repositório original do Guardiões Web


https://github.com/FGA-GCES/guardioes-web/issues/1
